/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package passenger;

import javax.swing.ImageIcon;
import main.JatraBegins;
import util.EditProfile;

/**
 *
 * @author USER
 */
public class PassengerDashBoard extends javax.swing.JFrame {

    /**
     * Creates new form PassengerDashBoard
     */
    public PassengerDashBoard() {
        initComponents();
        this.setLocationRelativeTo(null);
        JatraBegins.setPassenger_homepage(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        notification = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        editProfile = new javax.swing.JButton();
        support = new javax.swing.JButton();
        logOut = new javax.swing.JButton();
        changePass = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        busStopNearby = new javax.swing.JButton();
        searchBus = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 95, 238));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bus-logo-abstract_7315-17.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Jatra.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, 90));

        notification.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_appointment_reminders_filled_100px.png"))); // NOI18N
        notification.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                notificationMouseClicked(evt);
            }
        });
        jPanel1.add(notification, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, 40, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_user_male_circle_48px.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 70));

        jPanel2.setBackground(new java.awt.Color(192, 157, 245));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/DashBoardAi.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 70));

        editProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/EditProfileDefault.png"))); // NOI18N
        editProfile.setContentAreaFilled(false);
        editProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editProfileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editProfileMouseExited(evt);
            }
        });
        editProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editProfileActionPerformed(evt);
            }
        });
        jPanel2.add(editProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 240, 70));

        support.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Support.png"))); // NOI18N
        support.setContentAreaFilled(false);
        jPanel2.add(support, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, -1, -1));

        logOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LogOutDefault.png"))); // NOI18N
        logOut.setContentAreaFilled(false);
        logOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logOutMouseExited(evt);
            }
        });
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });
        jPanel2.add(logOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 240, 70));

        changePass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ChangePassDefault.png"))); // NOI18N
        changePass.setContentAreaFilled(false);
        changePass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                changePassMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                changePassMouseExited(evt);
            }
        });
        changePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePassActionPerformed(evt);
            }
        });
        jPanel2.add(changePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 240, 70));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 240, 570));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Bus Stops Nearby.png"))); // NOI18N
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 180, -1));

        busStopNearby.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Passenger Bus Stops Nearby Button.png"))); // NOI18N
        busStopNearby.setContentAreaFilled(false);
        busStopNearby.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busStopNearbyActionPerformed(evt);
            }
        });
        jPanel3.add(busStopNearby, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 230, 200));

        searchBus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Passenger Search Bus Button.png"))); // NOI18N
        searchBus.setContentAreaFilled(false);
        searchBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBusActionPerformed(evt);
            }
        });
        jPanel3.add(searchBus, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 230, 200));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Search Bus2.png"))); // NOI18N
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 120, -1));

        jLabel5.setFont(new java.awt.Font("Quicksand Light", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(144, 98, 213));
        jLabel5.setText("Welcome Back User!");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 680, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/DashboardHover.png"));
        jButton2.setIcon(i);
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/DashBoardAi.png"));
        jButton2.setIcon(i);
    }//GEN-LAST:event_jButton2MouseExited

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void editProfileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editProfileMouseEntered
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/EditProfileHover.png"));
        editProfile.setIcon(i);
    }//GEN-LAST:event_editProfileMouseEntered

    private void editProfileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editProfileMouseExited
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/EditProfileDefault.png"));
        editProfile.setIcon(i);
    }//GEN-LAST:event_editProfileMouseExited

    private void editProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editProfileActionPerformed

        this.setVisible(false);
        new EditProfile().setVisible(true);
    }//GEN-LAST:event_editProfileActionPerformed

    private void logOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutMouseEntered
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/LogOutHover.png"));
        logOut.setIcon(i);
    }//GEN-LAST:event_logOutMouseEntered

    private void logOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutMouseExited
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/LogOutDefault.png"));
        logOut.setIcon(i);
    }//GEN-LAST:event_logOutMouseExited

    private void changePassMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePassMouseEntered
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/ChangePassHover.png"));
        changePass.setIcon(i);
    }//GEN-LAST:event_changePassMouseEntered

    private void changePassMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePassMouseExited
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/ChangePassDefault.png"));
        changePass.setIcon(i);
    }//GEN-LAST:event_changePassMouseExited

    private void changePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePassActionPerformed

        this.setVisible(false);
        new util.ChangePassword().setVisible(true);
    }//GEN-LAST:event_changePassActionPerformed

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed
        new util.userPrompts.PromptExit(this).setVisible(true);
    }//GEN-LAST:event_logOutActionPerformed

    private void searchBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBusActionPerformed

        this.setVisible(false);
        new SearchBus().setVisible(true);
    }//GEN-LAST:event_searchBusActionPerformed

    private void busStopNearbyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busStopNearbyActionPerformed
        this.setVisible(false);
        new util.FindNearbyBusStop().setVisible(true);
    }//GEN-LAST:event_busStopNearbyActionPerformed

    private void notificationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notificationMouseClicked

    }//GEN-LAST:event_notificationMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PassengerDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PassengerDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PassengerDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PassengerDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        JatraBegins.setUser("passenger");

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PassengerDashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton busStopNearby;
    private javax.swing.JButton changePass;
    private javax.swing.JButton editProfile;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton logOut;
    private javax.swing.JLabel notification;
    private javax.swing.JButton searchBus;
    private javax.swing.JButton support;
    // End of variables declaration//GEN-END:variables
}
