/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package passenger;

import googlemapsapi.Address.AddressAPI;
import googlemapsapi.Places.NearbyBusStopsAPI;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import main.JatraBegins;
import util.PredictionsWindow;

/**
 *
 * @author USER
 */
public class SearchBus extends javax.swing.JFrame {

    //private MoreSettings profilePopup;
    private ArrayList<String> currentLocationPredictions;
    private ArrayList<String> destinedLocationPredictions;
    private static String currentlocation;
    private static String destinedlocation;
    private int sessiontoken = 123;

    public SearchBus() {
        initComponents();
        this.setLocationRelativeTo(null);

        //profilePopup = new MoreSettings();
        // JatraBegins.setPassenger_homepage(this);
        this.setLocationRelativeTo(null);
        // addComponentListener(this);
        validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        back = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        destSearch = new javax.swing.JButton();
        search = new javax.swing.JButton();
        currentSearch = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        DestinationField = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        LocationField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(181, 147, 229));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PreviousPage.png"))); // NOI18N
        back.setContentAreaFilled(false);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 600));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Destination.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Search Bus.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        destSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Search Button.png"))); // NOI18N
        destSearch.setContentAreaFilled(false);
        destSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destSearchActionPerformed(evt);
            }
        });
        jPanel2.add(destSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, -1, -1));

        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Search Default.png"))); // NOI18N
        search.setContentAreaFilled(false);
        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchMouseExited(evt);
            }
        });
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel2.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, -1, -1));

        currentSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Search Button.png"))); // NOI18N
        currentSearch.setContentAreaFilled(false);
        currentSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentSearchActionPerformed(evt);
            }
        });
        jPanel2.add(currentSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, -1, -1));

        jSeparator4.setForeground(new java.awt.Color(118, 41, 193));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 340, 10));

        DestinationField.setFont(new java.awt.Font("Quicksand Light", 0, 18)); // NOI18N
        DestinationField.setForeground(new java.awt.Color(153, 95, 238));
        DestinationField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        DestinationField.setBorder(null);
        DestinationField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DestinationFieldMouseClicked(evt);
            }
        });
        DestinationField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DestinationFieldActionPerformed(evt);
            }
        });
        jPanel2.add(DestinationField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 340, 30));

        jSeparator5.setForeground(new java.awt.Color(118, 41, 193));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 340, 10));

        LocationField.setFont(new java.awt.Font("Quicksand Light", 0, 18)); // NOI18N
        LocationField.setForeground(new java.awt.Color(153, 95, 238));
        LocationField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        LocationField.setBorder(null);
        LocationField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LocationFieldMouseClicked(evt);
            }
        });
        LocationField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LocationFieldActionPerformed(evt);
            }
        });
        jPanel2.add(LocationField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 340, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Current.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 90, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 670, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseEntered
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/Search Hover.png"));
        search.setIcon(i);
    }//GEN-LAST:event_searchMouseEntered

    private void searchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseExited
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/Search Default.png"));
        search.setIcon(i);
    }//GEN-LAST:event_searchMouseExited

    private void LocationFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LocationFieldActionPerformed

    }//GEN-LAST:event_LocationFieldActionPerformed

    private void LocationFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LocationFieldMouseClicked
    }//GEN-LAST:event_LocationFieldMouseClicked

    private void DestinationFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DestinationFieldActionPerformed

    }//GEN-LAST:event_DestinationFieldActionPerformed

    private void DestinationFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DestinationFieldMouseClicked
    }//GEN-LAST:event_DestinationFieldMouseClicked

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed

        this.setVisible(false);
        JatraBegins.getPassenger_homepage().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void currentSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentSearchActionPerformed
        String currentLocation = LocationField.getText();
        currentLocationPredictions = new AddressAPI(sessiontoken).findAddressFromQuery(currentLocation);
        new PredictionsWindow(currentLocationPredictions, "current", this).setVisible(true);
    }//GEN-LAST:event_currentSearchActionPerformed

    private void destSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destSearchActionPerformed
        String destinedLocation = DestinationField.getText();
        destinedLocationPredictions = new AddressAPI(sessiontoken).findAddressFromQuery(destinedLocation);
        new PredictionsWindow(destinedLocationPredictions, "destination", this).setVisible(true);
    }//GEN-LAST:event_destSearchActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        //radius = 1000 seems more sound
        new NearbyBusStopsAPI(1500).searchBusStopsNearby(null);
        // System.out.println("busStops searched nearby and put into file");

        new AvailableBusses().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_searchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchBus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DestinationField;
    private javax.swing.JTextField LocationField;
    private javax.swing.JButton back;
    private javax.swing.JButton currentSearch;
    private javax.swing.JButton destSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JButton search;
    // End of variables declaration//GEN-END:variables

    public void setLocationField(String str) {
        LocationField.setText(str);
    }

    public void setDestinationField(String str) {
        DestinationField.setText(str);
    }
}
