/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package util;

import database.dataBaseSQL;
import util.popUpWindows.WrongPassword;
import main.Owner;
import main.Passenger;
import main.User;
import util.popUpWindows.AccountCreated;
import util.popUpWindows.EmptyFields;
import util.popUpWindows.PasswordWeak;

/**
 *
 * @author USER
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form BasicDetails
     */
    public SignUp() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        userNameField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        phoneNumberField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        serviceTypeComboBox = new javax.swing.JComboBox<>();
        registerButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cityField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        confirmPasswordField = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        userNameField1 = new javax.swing.JTextField();
        registerButton1 = new javax.swing.JButton();
        previousButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(105, 214, 246));
        jPanel1.setPreferredSize(new java.awt.Dimension(726, 564));

        jPanel3.setBackground(new java.awt.Color(51, 57, 64));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userNameField.setBackground(new java.awt.Color(153, 153, 153));
        userNameField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        userNameField.setForeground(new java.awt.Color(255, 255, 255));
        userNameField.setBorder(null);
        jPanel3.add(userNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 140, 20));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(70, 165, 233));
        jLabel1.setText("Basic Details");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(70, 165, 233));
        jLabel2.setText("User Name");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(70, 165, 233));
        jLabel4.setText("Password");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(70, 165, 233));
        jLabel5.setText("Phone Number");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));

        phoneNumberField.setBackground(new java.awt.Color(153, 153, 153));
        phoneNumberField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        phoneNumberField.setBorder(null);
        jPanel3.add(phoneNumberField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 181, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(70, 165, 233));
        jLabel7.setText("Types of Service");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 394, -1, -1));

        serviceTypeComboBox.setBackground(new java.awt.Color(0, 0, 0));
        serviceTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Passenger", "Owner" }));
        serviceTypeComboBox.setBorder(null);
        jPanel3.add(serviceTypeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 432, 139, 25));

        registerButton.setBackground(new java.awt.Color(33, 33, 33));
        registerButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        registerButton.setForeground(new java.awt.Color(255, 255, 255));
        registerButton.setBorder(null);
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        jPanel3.add(registerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, 20, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(70, 165, 233));
        jLabel8.setText("Confirm password");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, -1, -1));

        emailField.setBackground(new java.awt.Color(153, 153, 153));
        emailField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        emailField.setBorder(null);
        jPanel3.add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 181, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(70, 165, 233));
        jLabel9.setText("Email");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(70, 165, 233));
        jLabel10.setText("City");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, -1, -1));

        cityField.setBackground(new java.awt.Color(153, 153, 153));
        cityField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cityField.setBorder(null);
        jPanel3.add(cityField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 181, 20));

        passwordField.setBackground(new java.awt.Color(153, 153, 153));
        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });
        jPanel3.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 181, -1));

        confirmPasswordField.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.add(confirmPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 181, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(70, 165, 233));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Add Image");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 90, 30));

        userNameField1.setBackground(new java.awt.Color(153, 153, 153));
        userNameField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        userNameField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userNameField1.setBorder(null);
        jPanel3.add(userNameField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 181, 20));

        registerButton1.setBackground(new java.awt.Color(33, 33, 33));
        registerButton1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        registerButton1.setForeground(new java.awt.Color(255, 255, 255));
        registerButton1.setText("Register");
        registerButton1.setBorder(null);
        registerButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(registerButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 490, 136, 51));

        previousButton.setBackground(new java.awt.Color(105, 214, 246));
        previousButton.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        previousButton.setForeground(new java.awt.Color(51, 57, 64));
        previousButton.setText("<");
        previousButton.setBorder(null);
        previousButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                previousButtonMouseClicked(evt);
            }
        });
        previousButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(previousButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(previousButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 766, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void previousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_previousButtonActionPerformed

    private void previousButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previousButtonMouseClicked

        new Login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_previousButtonMouseClicked

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_passwordFieldActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        char[] firstPass = passwordField.getPassword();
        char[] secondPass = confirmPasswordField.getPassword();

        String firstP = String.valueOf(firstPass);
        String secondP = String.valueOf(secondPass);

        //checks if all the fields are filled or not. If not filled then a pop up window appears.
        // if filled, then check if password satisfies the condition
        if (userNameField.getText().isEmpty() || phoneNumberField.getText().isEmpty()
                || cityField.getText().isEmpty() || String.valueOf(firstPass).isEmpty() || emailField.getText().isEmpty()) {
            new EmptyFields().setVisible(true);

        } else {

            if (firstP.length() < 8) {
                new PasswordWeak().setVisible(true);
            } else {

                if (firstP.equals(secondP)) {
                    System.out.println("matched password");

                    User user;
                    String service = serviceTypeComboBox.getSelectedItem().toString();
                    if (service.equals("Passenger")) {
                        user = new Passenger(userNameField.getText(), phoneNumberField.getText(), cityField.getText(), String.valueOf(firstPass), emailField.getText());
                    } else {
                        user = new Owner(userNameField.getText(), phoneNumberField.getText(), cityField.getText(), String.valueOf(firstPass), emailField.getText());
                    }
                    new AccountCreated(this).setVisible(true);

                    //if everything's correct, setup a connection to mySQL database and store the information
                    new dataBaseSQL(user).uploadData();

                } else {
                    // a pop window saying that password doesnt match
                    new WrongPassword().setVisible(true);
                    System.out.println("password doesnt match");
                }
            }
        }

    }//GEN-LAST:event_registerButtonActionPerformed

    private void registerButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cityField;
    private javax.swing.JPasswordField confirmPasswordField;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField phoneNumberField;
    private javax.swing.JButton previousButton;
    private javax.swing.JButton registerButton;
    private javax.swing.JButton registerButton1;
    private javax.swing.JComboBox<String> serviceTypeComboBox;
    private javax.swing.JTextField userNameField;
    private javax.swing.JTextField userNameField1;
    // End of variables declaration//GEN-END:variables
}
